@ProductManage.Presentation_HostAddress = https://localhost:7137

GET {{ProductManage.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ProductManage.Presentation_HostAddress}}/api/test

###
